Ruby/Testing/rails-testing/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :achievements do
    resources :encouragements, only: [:new, :create] do
    end
  end

  root to: 'welcome#index'
end

Ruby/Testing/rails-testing/app/models/achievement.rb
class Achievement < ApplicationRecord

  belongs_to :user

  has_many :encouragements

  validates :title, presence: true
  # validates :title, uniqueness: true
  # validate :unique_title_for_one_user
  validates :user, presence: true
  validates :title, uniqueness: {
      scope: :user_id,
      message: 'You can\'t have two same name achievements.'
  }

  enum privacy: [:public_access, :private_access, :friends_access]

  mount_uploader :cover_image, CoverImageUploader

  def description_html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end

  def silly_title
    "#{title} by #{user.email}"
  end

  def self.by_letter(letter)
    includes(:user).where('title LIKE ?', "#{letter}%").order('users.email')
  end

  private

  # def unique_title_for_one_user
  #   existing_achievement = Achievement.find_by(title: title)
  #   if existing_achievement && existing_achievement.user == user
  #     errors.add(:title, 'you can\t have two achievements with the same title')
  #   end
  # end

  def self.get_public_achievements
    self.public_access
  end
end

Ruby/Testing/rails-testing/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ruby/Testing/rails-testing/app/models/encouragement.rb
class Encouragement < ApplicationRecord
  belongs_to :user
  belongs_to :achievement

  validates :message, presence: true
end

Ruby/Testing/rails-testing/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :encouragements
end

Ruby/Testing/rails-testing/app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :owners_only, only: [:update, :edit, :destroy]

  def index
    @achievements = Achievement.get_public_achievements
  end

  def new
    @achievement = Achievement.new
  end

  def edit
  end

  def update
    if @achievement.update_attributes(achievements_params)
      redirect_to(achievement_path(@achievement))
    else
      render :edit
    end
  end

  def destroy
    @achievement.destroy
    redirect_to achievement_path
  end

  def create
    @achievement = Achievement.new(achievements_params)
    @achievement.user = current_user
    if @achievement.save
      UserMailer.achievement_created(current_user.email, @achievement.id).deliver_now
      redirect_to achievement_url(@achievement), notice: 'Achievement has been created.'
    else
      render :new
    end
    # service = CreateAchievement.new(achievements_params, current_user)
    # service.create
    # if service.created?
    #   redirect_to achievement_url(@achievement), notice: 'Achievement has been created.'
    # else
    #   render :new
    # end
  end

  def show
    @achievement = Achievement.find(params[:id])
  end

  private

  def achievements_params
    params.require(:achievement).permit(:title, :description, :privacy, :featured, :cover_image)
  end

  def owners_only
    @achievement = Achievement.find(params[:id])

    if current_user != @achievement.user
      redirect_to achievement_path
    end
  end

end

Ruby/Testing/rails-testing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Ruby/Testing/rails-testing/app/controllers/encouragements_controller.rb
class EncouragementsController < ApplicationController

  before_action :auth_user
  before_action :authors_not_allowed
  before_action :not_twice

  def new
    @encouragement = Encouragement.new
    render :new
  end

  private

  def auth_user
    @achievement = Achievement.find(params[:achievement_id])

    unless current_user
      redirect_to achievement_path(@achievement), alert: 'You must be logged in.'
      return
    end
  end

  def authors_not_allowed
    if current_user.id == @achievement.user.id
      redirect_to achievement_path(@achievement), alert: 'You can\'t encourage yourself.'
      return
    end
  end

  def not_twice
    if Encouragement.exists?(user: current_user, achievement: @achievement)
      redirect_to achievement_path(@achievement), alert: 'You can\' encourage twice.'
      return
    end
  end
end

Ruby/Testing/rails-testing/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

Ruby/Testing/rails-testing/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/Testing/rails-testing/app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>

    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k, v| [k.split('_').first.capitalize, k] }] %>
    <%= f.input :featured, label: 'Featured achievement' %>
    <%= f.input :cover_image, as: :file %>

    <%= f.submit 'Create Achievement', class: 'btn btn-primary' %>

<% end %>

Ruby/Testing/rails-testing/app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<div><%= @achievement.description_html.html_safe %></div>

<div class="encouragement">
  <h2>Encouragements</h2>

  <%= link_to 'Encourage', new_achievement_encouragement_path(@achievement), id: 'encourage-button' %>
</div>

Ruby/Testing/rails-testing/app/views/encouragements/new.html.erb
<%= simple_form_for [@encouragement, @achievement] do |f| %>

    <%= f.input :message, placeholder: 'Message' %>
    <%= f.submit 'Encourage' %>

<% end %>

Ruby/Testing/rails-testing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTesting</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="container-fluid">

  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rails testing</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'New Achievement', new_achievement_path %></li>
      </ul>
    </div>
  </nav>

  <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

Ruby/Testing/rails-testing/app/views/welcome/index.html.erb
<h1>Welcome bitch</h1>