Ruby/Rails/FirstProject/config/routes.rb
Rails.application.routes.draw do

  resources :answers
  resources :questions

  root 'home#index'

  get '/about' => 'home#about'

end

Ruby/Rails/FirstProject/app/models/answer.rb
class Answer < ApplicationRecord

  include HasGravatar

  belongs_to :question

end

Ruby/Rails/FirstProject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ruby/Rails/FirstProject/app/models/concerns/has_gravatar.rb
module HasGravatar

  def gravatar
    "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
  end

end

Ruby/Rails/FirstProject/app/models/question.rb
class Question < ApplicationRecord

  include HasGravatar

  has_many :answers

end

Ruby/Rails/FirstProject/app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create

    question = Question.find(params[:answer][:question_id])

    answer = question.answers.create(answer_params)

    MainMailer.create_notify_question_author(answer).deliver_later

    session[:current_user_email] = answer_params[:email]

    redirect_to question
  end

  private

  def answer_params
    params.require(:answer).permit(:email, :body, :question_id)
  end

end

Ruby/Rails/FirstProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

Ruby/Rails/FirstProject/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(:created_at => :desc).all
  end

  def about
  end

  def temp
    redirect_to root_path
  end
end

Ruby/Rails/FirstProject/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    Question.create(question_params)

    session[:current_user_email] = question_params[:email]

    redirect_to root_path
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc)
  end

  private

  def question_params
    params.require(:question).permit(:email, :body)
  end

end

Ruby/Rails/FirstProject/app/helpers/answers_helper.rb
module AnswersHelper
end

Ruby/Rails/FirstProject/app/helpers/application_helper.rb
module ApplicationHelper

  def current_user_email
    session[:current_user_email]
  end

end

Ruby/Rails/FirstProject/app/helpers/home_helper.rb
module HomeHelper
end

Ruby/Rails/FirstProject/app/helpers/questions_helper.rb
module QuestionsHelper
end

Ruby/Rails/FirstProject/app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsing-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Test Link</a>
    </div>

    <div class="collapse navbar-collapse" id="collapsing-navbar">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form>
            <a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">Ask Question</a>
          </form>
        </li>
      </ul>
    </div>

  </div>
</nav>

Ruby/Rails/FirstProject/app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">New Answer</h4>
      </div>

      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>

          <input type="hidden" name="answer[question_id]" value="<%= @question.id %>" />
          <div class="modal-body">

            <div class="form-group">
              <label for="inputEmail" class="col-sm-2 control-label">Email</label>
              <div class="col-sm-10">
                <input type="email" value="<%= current_user_email %>" name="answer[email]" class="form-control" id="inputEmail" placeholder="Email" required>
              </div>
            </div>
            <div class="form-group">
              <label for="inputAnswer" class="col-sm-2 control-label">Answer</label>
              <div class="col-sm-10">
                <textarea class="form-control" name="answer[body]" id="inputAnswer" placeholder="Whats the answer?" required></textarea>
              </div>
            </div>

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>

      <% end %>

    </div>
  </div>
</div>

Ruby/Rails/FirstProject/app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">New Question</h4>
      </div>

      <!--<form class="form-horizontal" action="/questions" method="post">-->

      <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>

        <div class="modal-body">

          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" value="<%= current_user_email %>" name="question[email]" class="form-control" id="inputEmail" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="question[body]" id="inputQuestion" placeholder="What would you like to know" required></textarea>
            </div>
          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>

      <% end %>

    </div>
  </div>
</div>

Ruby/Rails/FirstProject/app/views/home/about.html.erb
<h1>About</h1>

<div class="well">
  <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Phasellus convallis consectetur massa, eu convallis magna interdum in.
    Sed ut venenatis quam. Sed non tortor ac sapien cursus suscipit id ut felis.</p>
</div>

<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://www.gravatar.com/avatar/424242">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">user@email.com asked:</h4>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Phasellus convallis consectetur massa, eu convallis magna interdum in.
    Sed ut venenatis quam. Sed non tortor ac sapien cursus suscipit id ut felis.
  </div>
</div>

<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://www.gravatar.com/avatar/424242">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">user@email.com asked:</h4>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Phasellus convallis consectetur massa, eu convallis magna interdum in.
    Sed ut venenatis quam. Sed non tortor ac sapien cursus suscipit id ut felis.
  </div>
</div>
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://www.gravatar.com/avatar/424242">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">user@email.com asked:</h4>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Phasellus convallis consectetur massa, eu convallis magna interdum in.
    Sed ut venenatis quam. Sed non tortor ac sapien cursus suscipit id ut felis.
  </div>
</div>

Ruby/Rails/FirstProject/app/views/home/index.html.erb
<h1>Welcome</h1>

<div class="well">
  <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Phasellus convallis consectetur massa, eu convallis magna interdum in.
    Sed ut venenatis quam. Sed non tortor ac sapien cursus suscipit id ut felis.</p>
</div>

<% @questions.each do |question| %>

    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="<%= question.gravatar %>">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= question.email %> asked:</h4>
        <%= time_ago_in_words question.created_at %> ago
        <br>
        <%= question.body %>
        <div>
          <a href="<%= question_path(question) %>" class="btn btn-success btn-xs">View Answers</a>
        </div>
      </div>
    </div>

<% end %>

<% if @questions.empty? %>
    <div class="alert alert-info">Nothing here yet.</div>
<% end %>

Ruby/Rails/FirstProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


</head>

<body>

  <%= render 'home/navbar' %>

  <div class="well">
    <%= current_user_email %>
  </div>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'home/new_question_form' %>

</body>
</html>

Ruby/Rails/FirstProject/app/views/questions/show.html.erb
<div class="lead well">
  <div class="media">
    <div class="media-left">
      <a href="#">
        <img class="media-object" src="<%= @question.gravatar %>">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= @question.email %> asked:</h4>
      <%= time_ago_in_words @question.created_at %> ago
      <br>
      <%= @question.body %>
      <div>
        <a href="<%= question_path(@question) %>" class="btn btn-success btn-xs">View Answers</a>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

    <div>
      <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit
        new answer
      </button>
    </div>

    <%= render 'home/new_answer_form' %>

    <% @answers.each do |answer| %>

        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="<%= answer.gravatar %>">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= answer.email %> asked:</h4>
            <%= time_ago_in_words answer.created_at %> ago
            <br>
            <%= answer.body %>
          </div>
        </div>

    <% end %>

    <% if @answers.empty? %>
        <div class="alert alert-info">Nothing here yet.</div>
    <% end %>

  </div>
</div>